### ISSUE TITLE
video qa

### ISSUE THREAD

**Issue by anoy131** [JieyuZ2/TaskMeAnything#4]
Hi, your code is excellent! I would like to ask when you can share the code about video qa evaluation?

**Comment by weikaih04** [comment]
Hi,
Thank you for your interest! Since most video QA models are not supported by Hugging Face and require adding new repositories as submodules, we do not include them to keep the main branch codebase clean.

We have added a video model branch with a new README. Check out the [videoqa model branch](https://github.com/JieyuZ2/TaskMeAnything/tree/videoqa_model) to use our video QA models.
